title: "QU30 - Blog"
description: "A blog talking about coding, Minecraft, cats, etc."
remote_theme: "abhinavs/moonwalk"
plugins:
  - jekyll-remote-theme
markdown: kramdown

minima:
  skin: dark

exclude:
  - README.md
  - .github
  - CNAME
